"""initial schema

Revision ID: 44d8ad178fb9
Revises: 
Create Date: 2026-06-06 15:52:10.360904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d8ad178fb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier',
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('fleet_type', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('carrier_id')
    )
    op.create_table('criterion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('records_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('swara_config_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment',
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('carrier_id', sa.Integer(), nullable=True),
    sa.Column('pickup_window_start', sa.DateTime(), nullable=True),
    sa.Column('delivery_window_end', sa.DateTime(), nullable=True),
    sa.Column('actual_delivery_time', sa.DateTime(), nullable=True),
    sa.Column('client_rating', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('has_gps', sa.Boolean(), nullable=True),
    sa.Column('has_pod', sa.Boolean(), nullable=True),
    sa.Column('accident_severity', sa.String(length=20), nullable=True),
    sa.Column('carrier_fault', sa.Boolean(), nullable=True),
    sa.Column('claim_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.carrier_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_carrier_id'), ['carrier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_status'), ['status'], unique=False)

    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('initiated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('scenario_criterion',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['criterion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scenario_id', 'criterion_id')
    )
    op.create_table('run_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carrier.carrier_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_result_carrier_id'), ['carrier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_result_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_result_run_id'))
        batch_op.drop_index(batch_op.f('ix_run_result_carrier_id'))

    op.drop_table('run_result')
    op.drop_table('scenario_criterion')
    with op.batch_alter_table('run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_scenario_id'))

    op.drop_table('run')
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_status'))
        batch_op.drop_index(batch_op.f('ix_shipment_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_carrier_id'))

    op.drop_table('shipment')
    op.drop_table('scenario')
    op.drop_table('user')
    op.drop_table('dataset')
    op.drop_table('criterion')
    op.drop_table('carrier')
    # ### end Alembic commands ###
